# Generated by Django 5.2.6 on 2025-10-22 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50)),
                ('sport_type', models.CharField(choices=[('basketball', 'Basketball'), ('futsal', 'Futsal'), ('soccer', 'Soccer'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('baseball', 'Baseball'), ('volleyball', 'Volleyball'), ('padel', 'Padel'), ('golf', 'Golf'), ('football', 'Football'), ('softball', 'Softball'), ('table_tennis', 'Table Tennis')], default='basketball', max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='scheduled_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
