# Generated by Django 5.2.7 on 2025-10-20 11:51

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescheduler',
            name='id',
            field=models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False),
        ),
    ]
