# Generated by Django 5.2.7 on 2025-10-21 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_scheduler', '0002_alter_gamescheduler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescheduler',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
