# Generated by Django 5.2.7 on 2025-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_scheduler', '0003_alter_gamescheduler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescheduler',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
