# Generated by Django 5.2.7 on 2025-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_scheduler', '0004_alter_gamescheduler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescheduler',
            name='sport_type',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('futsal', 'Futsal'), ('soccer', 'Soccer'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('baseball', 'Baseball'), ('volleyball', 'Volleyball'), ('padel', 'Padel'), ('golf', 'Golf'), ('football', 'Football'), ('softball', 'Softball'), ('table_tennis', 'Table Tennis')], default='basketball', max_length=50),
        ),
    ]
