# Generated by Django 5.2.6 on 2025-10-22 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('futsal', 'Futsal')], max_length=20, verbose_name='Jenis Lapangan'),
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
