# Generated by Django 5.2.6 on 2025-10-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Facility')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('futsal', 'Futsal'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('baseball', 'Baseball'), ('volleyball', 'Volleyball'), ('padel', 'Padel'), ('golf', 'Golf'), ('football', 'Football'), ('softball', 'Softball'), ('other', 'Other')], max_length=20, verbose_name='Jenis Lapangan'),
        ),
        migrations.AddField(
            model_name='court',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='court_filter.facility', verbose_name='Facilities'),
        ),
    ]
