# Generated by Django 5.2.7 on 2025-10-21 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Facility')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Province')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Court Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('court_type', models.CharField(choices=[('basketball', 'Basketball'), ('futsal', 'Futsal'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('baseball', 'Baseball'), ('soccer', 'Soccer'), ('volleyball', 'Volleyball'), ('padel', 'Padel'), ('golf', 'Golf'), ('football', 'Football'), ('softball', 'Softball'), ('other', 'Other')], max_length=20, verbose_name='Sport Type')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price/hour')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='court_photos/', verbose_name='Court Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('facilities', models.ManyToManyField(blank=True, to='manage_court.facility', verbose_name='Facilities')),
                ('provinces', models.ManyToManyField(related_name='courts', to='manage_court.province', verbose_name='Provinces')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=3)),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='review_photos/', verbose_name='Photo Review')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='manage_court.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['latitude', 'longitude'], name='manage_cour_latitud_153f80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('court', 'user')},
        ),
    ]
