# Generated by Django 5.2.7 on 2025-10-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_court', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='operational_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Operational Hours'),
        ),
    ]
