# Generated by Django 5.2.7 on 2025-10-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_court', '0002_court_operational_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='court',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
