# Generated by Django 5.2.7 on 2025-10-22 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_court', '0004_court_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='provinces',
        ),
        migrations.AddField(
            model_name='court',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='manage_court.province', verbose_name='Province'),
        ),
    ]
