# Generated by Django 5.2.7 on 2025-10-22 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_court', '0005_remove_court_provinces_court_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('futsal', 'Futsal'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('baseball', 'Baseball'), ('volleyball', 'Volleyball'), ('padel', 'Padel'), ('golf', 'Golf'), ('football', 'Football'), ('softball', 'Softball'), ('other', 'Other')], max_length=20, verbose_name='Sport Type'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
