# Generated by Django 5.2.6 on 2025-10-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_fix_author_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Optional thumbnail image URL'),
        ),
    ]
