# Generated by Django 5.2.7 on 2025-10-21 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court_name', models.CharField(help_text='Nama lapangan yang dilaporkan', max_length=255)),
                ('masalah', models.CharField(help_text='Nama lapangan yang dilaporkan', max_length=255)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='complain_photos/')),
                ('status', models.CharField(choices=[('DITINJAU', 'Ditinjau'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='DITINJAU', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
