# Generated by Django 5.2.7 on 2025-10-22 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court_name', models.CharField(help_text='Court Name', max_length=255)),
                ('masalah', models.CharField(help_text='Main Problem', max_length=255)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='complain_photos/')),
                ('status', models.CharField(choices=[('IN REVIEW', 'in review'), ('IN PROCESS', 'in process'), ('DONE', 'done')], default='IN REVIEW', max_length=20)),
                ('komentar', models.TextField(blank=True, help_text='Komentar admin terkait laporan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
