# Generated by Django 5.2.7 on 2025-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentikasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtuser',
            name='role',
            field=models.CharField(choices=[('user', 'Registered User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='courtuser',
            name='preference',
            field=models.CharField(choices=[('Outdoor', 'outdoor'), ('Indoor', 'indoor'), ('Both', 'both')], default='Both', max_length=10),
        ),
    ]
