# Generated by Django 5.2.7 on 2025-10-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentikasi', '0002_courtuser_role_alter_courtuser_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtuser',
            name='preference',
            field=models.CharField(choices=[('Outdoor', 'outdoor'), ('Indoor', 'indoor'), ('Both', 'indoor and outdoor')], default='Both', max_length=10),
        ),
    ]
