name: Push to PWS

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push to PWS (main -> master)
        env:
          PWS_URL: ${{ secrets.PWS_URL }}
        run: |
          set -eo pipefail
          # Ensure we only run from main for safety
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          if [[ "${GITHUB_REF_NAME}" != "main" ]]; then
            echo "This workflow only pushes from 'main'. Current: ${GITHUB_REF_NAME}"
            exit 0
          fi

          # Add remote alias 'pws' and push exactly like local
          git remote add pws "$PWS_URL" 2>/dev/null || git remote set-url pws "$PWS_URL"
          echo "Pushing: main -> master (remote: pws)"
          push_output=$(git push pws main:master 2>&1) || {
            echo "Push failed with output: $push_output"
            echo "Error: Unable to push changes. Please check the error message above and resolve any conflicts manually."
            exit 1
          }
          echo "Push successful with output: $push_output"
